### ISSUE TITLE
Prevent datagram fragmentation during first registration

### ISSUE THREAD

**Issue by EduardPon** [ARMmbed/mbed-client#215]
In case the data size of a registration exceeds the 1510 bytes, the datagram in the IPv6 stack will be fragmented. If the client device has not communicated with its destination device before (in this case the server), fragments will be dropped until the address resolution is finished. See also [https://github.com/ARMmbed/sal-stack-nanostack/issues/11#issuecomment-215640678].

The CoAP retry by re-sending the complete registration datagram will recover from the fragment drop. I would propose to avoid fragmentation and split up datagram in the multiple CoAP messages.

**Comment by yogpan01** [comment]
Hi, This needs to be checked on end-to-end level because mbed-client supports Blockwise CoAP message transfer but this is a unique case where the initial registration message is fragmented, so it can be issue from server side as well if it is not handling this use case.
We will check this and get back with fix proposal.

**Comment by kjbracey-arm** [comment]
Off-topic from mbed-client, but I'll respond to the initial report here.

To pin down the issue a little tighter - it's not a client->destination association issue. It's more precisely:

"If any of the nodes on the path from the client to the destination have not communicated with their next-hop node before, fragments may be dropped until their address resolution for the next hop is finished."

So you shouldn't see this with every node start up on a 6LoWPAN mesh. All nodes after the first should find the path to the common server clear, as all nodes across the mesh to the border router have definitely got their links up, and the border router will have a path to the server.

Multiple nodes on Ethernet would show the issue, as each of them would need to do their own resolution. 

In that case, if the server's not local, then if you could ensure the Ethernet segment's default router includes the Source Link-Layer Address option in its Router Advertisements, you could avoid the need for resolution.

DTLS would also side-step the issue, as the DTLS handshake would be small packets.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-727

**Comment by anttiylitokola** [comment]
Hi Ed, 

We have published fixes for blockwise operation. Could you try is your use case working any better now? Fixes are in yotta so yotta up should fetch the changes.

Thanks,
Antti

**Comment by EduardPon** [comment]
Hello,

These are the versions I have used to test:

|_ mbed-client 1.12.2
| |_ mbed-client-c 2.7.1 yotta_modules\mbed-client-c
| | \_ nanostack-libservice 3.5.1 yotta_modules\nanostack-libservice
| |_ mbed-trace 1.1.3 yotta_modules\mbed-trace
| |_ mbed-client-mbed-os 3.0.0 yotta_modules\mbed-client-mbed-os

But unfortunately I still see fragmentation on the Ethernet layer and not in the CoAP layer. Do I need to enable the blockwise implementation in a config file?

**Comment by anttiylitokola** [comment]
Hi, blockwise feature is disabled by default so you need to add following flag in config.json.
"coap_max_blockwise_payload_size": 1024
Acceptable values for the coap_max_blockwise_payload_size flag are:
0, 16, 32, 64, 128, 256, 512 and 1024. Value 0 means that the feature is not used.
https://docs.mbed.com/docs/mbed-client-guide/en/latest/Introduction/

**Comment by anttiylitokola** [comment]
Hi Ed, 
Is this duplicate to one you created in mbed-client-c repository?
https://github.com/ARMmbed/mbed-client-c/issues/52
If so maybe we can close this one.

**Comment by EduardPon** [comment]
Indirectly yes. The mbed-client code of LWM2M is not responsible for the "invalid payload bytes #52".

I assume that if a fix is required in CoAP, this is will be done in mbed-client-c and not in the mbed-client one. That's why I created a new issue in this repository. Also to keep issue reports clean and not stacking of issues in one report. Thanks.
